# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.6.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.6.0/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/hj/Program/autoClassify

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/hj/Program/autoClassify

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.6.0/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.6.0/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hj/Program/autoClassify/CMakeFiles /Users/hj/Program/autoClassify/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hj/Program/autoClassify/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named autoClassify

# Build rule for target.
autoClassify: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 autoClassify
.PHONY : autoClassify

# fast build rule for target.
autoClassify/fast:
	$(MAKE) -f CMakeFiles/autoClassify.dir/build.make CMakeFiles/autoClassify.dir/build
.PHONY : autoClassify/fast

AutoWork.o: AutoWork.cpp.o

.PHONY : AutoWork.o

# target to build an object file
AutoWork.cpp.o:
	$(MAKE) -f CMakeFiles/autoClassify.dir/build.make CMakeFiles/autoClassify.dir/AutoWork.cpp.o
.PHONY : AutoWork.cpp.o

AutoWork.i: AutoWork.cpp.i

.PHONY : AutoWork.i

# target to preprocess a source file
AutoWork.cpp.i:
	$(MAKE) -f CMakeFiles/autoClassify.dir/build.make CMakeFiles/autoClassify.dir/AutoWork.cpp.i
.PHONY : AutoWork.cpp.i

AutoWork.s: AutoWork.cpp.s

.PHONY : AutoWork.s

# target to generate assembly for a file
AutoWork.cpp.s:
	$(MAKE) -f CMakeFiles/autoClassify.dir/build.make CMakeFiles/autoClassify.dir/AutoWork.cpp.s
.PHONY : AutoWork.cpp.s

Config.o: Config.cpp.o

.PHONY : Config.o

# target to build an object file
Config.cpp.o:
	$(MAKE) -f CMakeFiles/autoClassify.dir/build.make CMakeFiles/autoClassify.dir/Config.cpp.o
.PHONY : Config.cpp.o

Config.i: Config.cpp.i

.PHONY : Config.i

# target to preprocess a source file
Config.cpp.i:
	$(MAKE) -f CMakeFiles/autoClassify.dir/build.make CMakeFiles/autoClassify.dir/Config.cpp.i
.PHONY : Config.cpp.i

Config.s: Config.cpp.s

.PHONY : Config.s

# target to generate assembly for a file
Config.cpp.s:
	$(MAKE) -f CMakeFiles/autoClassify.dir/build.make CMakeFiles/autoClassify.dir/Config.cpp.s
.PHONY : Config.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/autoClassify.dir/build.make CMakeFiles/autoClassify.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/autoClassify.dir/build.make CMakeFiles/autoClassify.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/autoClassify.dir/build.make CMakeFiles/autoClassify.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... autoClassify"
	@echo "... AutoWork.o"
	@echo "... AutoWork.i"
	@echo "... AutoWork.s"
	@echo "... Config.o"
	@echo "... Config.i"
	@echo "... Config.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

